project_name: "nixcfg"
default_status: "Backlog"
statuses: ["Backlog", "In Progress", "Blocked", "Done"]
labels: ["Security", "Tech-debt",]
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "hx"
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: true
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
